name: Daily Doodle Bot

on:
  push:
    branches: [main] # Change this to [master] if your default branch is master
  schedule:
    - cron: '0 16 * * *'
  workflow_dispatch:

jobs:
  run-doodle:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - run: npm install
      - name: Execute Script
        env:
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_HOLIDAY_WEBHOOK }} 
        run: node daily-doodle.mjs
